{
 "title": "Nucleus iDRAC Servers",
 "description": "SNMP Based Dashboard to Monitor Dell Hosts via iDRAC from orginal dashboard by ilovepancakes95 \nAdapted to flux by cybaen",
 "tags": [
  "idrac",
  "telegraf",
  "snmp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "idrac_host",
    "label": "iDRAC Host",
    "query": {
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart)\r\n|> keyValues(keyColumns: [\"system-name\"])\r\n|> keep(columns: [\"system-name\"])\r\n|> distinct(column: \"host\")\r\n|> group()\r\n"
    }
   },
   { "name": "bucket", "label": "Bucket", "query": "idrac" },
   { "name": "hostslist_key", "query": "idrac-hosts" }
  ]
 },
 "panels": [
  { "title": "iDRAC Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Local Time",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r._field == \"system-servicetag\" or r._field == \"system-model\" or r._field == \"power-state\" or r._field == \"system-globalstatus\" or r._field == \"system-uptime\" or r._field == \"idrac-url\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> unique(column: \"system-name\")\r\n|> keep(columns: [\"system-name\", \"system-servicetag\", \"system-model\", \"power-state\",\"system-globalstatus\",\"system-uptime\",\"idrac-url\"])\r\n|> group()\r\n|> sort(columns: [\"system-name\"], desc: false)",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status Map",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "[[tag_system-name]]",
     "groupBy": [
      { "params": [ "system-name" ], "type": "tag" }
     ],
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"system-globalstatus\")\r\n|> group(columns: [\"_field\", \"system-name\"]) // Group by field and system name\r\n|> keep(columns: [\"_time\", \"_value\", \"system-name\"])\r\n|> sort(columns: [\"system-name\", \"_time\"], desc: false)\r\n|> aggregateWindow(every:5m, fn:last)",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "# of iDRACs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart)\r\n|> keyValues(keyColumns: [\"system-name\"])\r\n|> keep(columns: [\"system-name\"])\r\n|> distinct(column: \"host\")\r\n|> group()\r\n|> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "$idrac_host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "idrac_host" },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"system-uptime\")\r\n",
     "select": [
      [
       { "params": [ "system-uptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "//SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"system-globalstatus\")\r\n",
     "select": [
      [
       { "params": [ "system-globalstatus" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "//SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"power-state\")\r\n",
     "select": [
      [
       { "params": [ "power-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "//SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"system-servicetag\")\r\n|> filter(fn: (r) => r._field == \"system-servicetag\")",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Watts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "System Watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"system-watts\")\r\n|> drop(columns:[\"agent_host\",\"host\", \"system-name\"])",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field =~ /^cpu[0-9]-temp$/)\r\n|> drop(columns:[\"agent_host\",\"host\", \"system-name\"])\r\n|> toFloat()\r\n|> map(fn: (r) => ({r with _value: r._value / 10.0}))\r\n",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "PSU Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "//SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"power-state\")\r\n",
     "select": [
      [
       { "params": [ "psu-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CMOS Battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"cmos-batterystate\")\r\n",
     "select": [
      [
       { "params": [ "cmos-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAID Battery",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"raid-batterystate\")\r\n",
     "select": [
      [
       { "params": [ "raid-batterystate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "BIOS Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"bios-version\")\r\n",
     "select": [
      [
       { "params": [ "bios-version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"storage-status\")\r\n",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"memory-status\")\r\n",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Thermal Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"temp-status\")\r\n",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Intrusion",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"intrusion-sensor\")\r\n",
     "select": [
      [
       { "params": [ "intrusion-sensor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "OS Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"system-osname\" or r._field == \"system-osversion\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> unique(column: \"system-osname\")\r\n|> keep(columns: [\"system-osname\", \"system-osversion\"])\r\n|> group()\r\n|> sort(columns: [\"system-osname\"], desc: false)",
     "select": [
      [
       { "params": [ "system-osname" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Log Entries",
   "type": "table",
   "gridPos": { "h": 19, "w": 9, "x": 7, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "log-number" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "//SELECT \"log-dates\" FROM \"idrac-hosts\" WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter GROUP BY \"log-number\" LIMIT 1\r\nfrom(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"log-dates\" or r[\"_field\"] == \"log-entry\" or r[\"_field\"] == \"log-severity\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> unique(column: \"log-dates\")\r\n|> keep(columns: [ \"log-dates\",\"log-entry\",\"log-severity\"])\r\n|> group()\r\n|> sort(columns: [\"log-dates\"], desc: true)\r\n",
     "select": [
      [
       { "params": [ "log-dates" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Inlet Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"inlet-temp\" or r._field == \"exhaust-temp\")\r\n|> drop(columns:[\"agent_host\",\"host\", \"system-name\"])\r\n|> toFloat()\r\n|> map(fn: (r) => ({r with _value: r._value / 10.0}))",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Physical Disk Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disks-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field == \"disks-capacity\" or r._field == \"disks-state\" or r._field == \"disks-predictivefail\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> unique(column: \"disks-name\")\r\n|> keep(columns: [\"disks-name\", \"disks-capacity\", \"disks-state\",\"disks-predictivefail\"])\r\n|> group()\r\n|> sort(columns: [\"disks-name\"], desc: false)",
     "select": [
      [
       { "params": [ "disks-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Fan 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"_measurement\"] == \"${hostslist_key}\")\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r._field =~ /^fan[0-9]-speed$/)\r\n|> drop(columns:[\"agent_host\",\"host\", \"system-name\"])\r\n",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "nic-name" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "idrac-hosts",
     "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart, stop: now())\r\n|> filter(fn: (r) => r[\"system-name\"] == \"${idrac_host}\")\r\n|> filter(fn: (r) => r[\"_field\"] == \"nic-current_mac\" or r[\"_field\"] == \"nic-status\" or r[\"_field\"] == \"nic-vendor\")\r\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> unique(column: \"nic-name\")\r\n|> keep(columns: [\"nic-name\", \"nic-current_mac\", \"nic-status\",\"nic-vendor\"])\r\n|> group()\r\n|> sort(columns: [\"nic-name\"], desc: false)",
     "select": [
      [
       { "params": [ "nic-vendor" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  }
 ]
}