{
 "title": "Redfish exporter",
 "description": "Dashboard for custom prometheus exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(redfish_exporter_general_info, job)"
   }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Power comsumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redfish_exporter_power_comsumption{job=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Disk with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count(redfish_exporter_disk{job=\"$instance\"} < 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Controller with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "count(redfish_exporter_controller{job=\"$instance\"} < 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Fans with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(redfish_exporter_fan{job=\"$instance\"} < 2) or vector(0)"
    }
   ]
  },
  {
   "title": "PS with errors",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "count(redfish_exporter_power_supply{job=\"$instance\"} < 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "redfish_exporter_thermal_location{job=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_status{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_power{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tag version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_info{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Tag version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_info{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "General Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_health{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fan state",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_fan_redundancy{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "General State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redfish_exporter_general_state{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temperatures (degres)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_thermal_location{job=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk states / health",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "redfish_exporter_disk{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_fan_rpm{job=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power comsumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redfish_exporter_power_comsumption{job=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}